env:
  browser: true
  es2021: true
  jest/globals: true,
extends:
  - 'plugin:react/recommended'
  - airbnb
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
settings:
  import/resolver:
    node:
      extensions: ['.js', '.jsx', '.ts', '.tsx']
      paths: ['./src']

plugins:
  - react
  - '@typescript-eslint'
  - 'jest'
rules: {
   "import/extensions": [
      "error",
      "ignorePackages",
      {
        "js": "never",
        "jsx": "never",
        "ts": "never",
        "tsx": "never"
      }
    ],
    'no-use-before-define': 'off',
    '@typescript-eslint/no-use-before-define': ['error'],
    'react/jsx-filename-extension': [2, { 'extensions': ['.js', '.jsx', '.ts', '.tsx'] }],
    'react/jsx-one-expression-per-line': 'off',
    "import/prefer-default-export": 'off',
    "arrow-body-style": ["error", "always"],
    "dot-notation": [2, {"allowKeywords": true,  "allowPattern": "^[a-z]+(_[a-z]+)+$" }],
    "jsx-a11y/media-has-caption": 0
}
